version: "3"
services:
    web:
        build: .
        volumes:
            - './app/static/resources/data_collection:/data_collection'
        environment:
            FLASK_DEBUG: 1
            FLASK_ENV: development
            FLASK_APP: run.py
        ports:
            - '5000:5000'
        entrypoint:
            - flask
            - run
            - --host=0.0.0.0
